import{S as b,a as L,i as d}from"./assets/vendor-b42c18af.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const w=new b(".gallery a",{captionsData:"alt",captionDelay:250});document.querySelector(".gallery");function S({webformatURL:r,largeImageURL:t,tags:a,likes:s,views:e,comments:o,downloads:i}){return` 
  <li class="gallery-item">
    <a class="gallery-link" href="${t}">
      <img class="gallery-image" src="${r}" alt="${a}" />
      <div class="wrap">
        <p><b>Likes:</b> </br>${s}</p>
        <p><b>Views:</b> </br>${e}</p>
        <p><b>Coments:</b> </br>${o}</p>
        <p><b>Downloads:</b> </br>${i}</p>
      </div>
    </a>
  </li>`}function q(r){return r.map(S).join("")}function p(r,t){r.insertAdjacentHTML("beforeend",q(t)),w.refresh()}const v="https://pixabay.com/api/",P="42803538-255c2e80da4c06c2048b9f703";let $=1,C=15;async function m(r){const t={key:P,q:r,_page:$,_limit:C,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await L.get(`${v}/`,{params:t})).data}const E=document.querySelector(".search-form"),c=document.querySelector(".loader"),f=document.querySelector(".gallery"),n=document.querySelector(".load-more-btn");h();let l,u=1;E.addEventListener("submit",async r=>{if(r.preventDefault(),f.innerHTML="",u=1,l=r.target.elements.search.value.trim(),l===""){d.warning({titleColor:"#fff",messageColor:"#fff",backgroundColor:"#ffa000",message:"Please enter a search query",position:"topRight"});return}g();try{const t=await m(l,u);if(t.hits.length===0)return h(),d.error({title:"Error",titleColor:"#fff",messageColor:"#fff",backgroundColor:"#ef4040",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});p(f,t.hits),M()}catch(t){console.log(t)}finally{y()}r.target.reset()});function g(){c&&(c.style.display="block")}function y(){c&&(c.style.display="none")}function h(){n&&(n.style.display="none")}function M(){n&&(n.style.display="block")}n.addEventListener("click",async r=>{g(),u+=1;const t=await m(l);p(f,t.hits),y();const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})});
//# sourceMappingURL=commonHelpers.js.map
